import type { CustomFood, DietPattern } from '../db/schema';
import type { Cuisine } from './cuisines';

/**
 * The food table.
 *
 * Curated by hand, like the exercise library, and for the same reason: the
 * fields that matter here are a realistic household serving and an honest
 * macro split, and open food datasets are full of barcode entries with neither.
 *
 * Every dish carries the region it belongs to, and the app asks her country
 * once so it can lead with hers. A woman eating roti, daal and salan every day
 * should not have to translate her dinner into chicken and broccoli to use a
 * food log - and neither should a woman eating jollof, adobo or tortillas. A
 * protein target you cannot hit with the food actually in your kitchen is a
 * target you abandon in a fortnight.
 *
 * Nothing is ever *hidden* by region. The region decides the order of a list
 * and which anchors a generated day reaches for first; every food stays
 * searchable, because plenty of people cook outside their postcode.
 *
 * Values are per the stated serving, from composition tables (USDA FoodData
 * Central and the Indian Food Composition Tables), rounded. Home cooking
 * varies - a karahi made with half a cup of oil is not the karahi below - so
 * these are planning numbers, and the UI says so.
 */

export type Allergen =
  | 'meat'
  | 'pork'
  | 'fish'
  | 'egg'
  | 'dairy'
  | 'gluten'
  | 'nuts'
  | 'soy';

export type FoodGroup = 'protein' | 'carb' | 'veg' | 'fruit' | 'dairy' | 'fat' | 'mixed';

export interface Food {
  id: string;
  name: string;
  /** How she would actually describe one portion. */
  serving: string;
  servingG: number;
  kcal: number;
  proteinG: number;
  carbG: number;
  fatG: number;
  fibreG: number;
  /** Approximate. Included because iron deficiency is common in women. */
  ironMg: number;
  contains: Allergen[];
  group: FoodGroup;
  /**
   * Where this is an everyday food. Absent means everywhere: eggs, rice,
   * yogurt, oats and chicken breast are nobody's regional speciality, and
   * tagging them would push them below a dish she eats twice a year.
   */
  cuisines?: Cuisine[];
  /**
   * What else she might type looking for it. Searching "lentils" and being
   * told the table has nothing is what makes a curated table feel small;
   * it has daal, it just does not spell it that way.
   */
  aliases?: string[];
  /**
   * Something a person eats between meals, as it comes.
   *
   * An opt-in tag rather than a rule about groups, because the rule produced
   * "Snack: 50 g of cooked chicken breast". The arithmetic was right - it is
   * under the calorie ceiling and it is a protein - and nobody has ever
   * snacked on half a chicken breast.
   */
  snack?: boolean;
  /**
   * Powder, not food. It stays in the search and in the protein-gap list,
   * where it is genuinely the best answer, and it is barred from anchoring a
   * meal: a planner that opens lunch with a scoop of whey is a planner that
   * has confused hitting a number with feeding somebody.
   */
  supplement?: boolean;
}

export const FOODS: Food[] = [
  /* ------------------------- South Asian staples ------------------------- */
  {
    id: 'roti',
    name: 'Roti / chapati',
    serving: '1 medium',
    servingG: 40,
    kcal: 104,
    proteinG: 3.4,
    carbG: 20,
    fatG: 1.2,
    fibreG: 3,
    ironMg: 1.2,
    contains: ['gluten'],
    group: 'carb',
    aliases: ['chapati', 'phulka', 'flatbread', 'wheat bread'],
    cuisines: ['south-asian'],
  },
  {
    id: 'naan',
    name: 'Naan',
    serving: '1 piece',
    servingG: 90,
    kcal: 262,
    proteinG: 8.7,
    carbG: 45,
    fatG: 5.1,
    fibreG: 2,
    ironMg: 2.2,
    contains: ['gluten', 'dairy'],
    group: 'carb',
    aliases: ['flatbread'],
    cuisines: ['south-asian'],
  },
  {
    id: 'paratha',
    name: 'Paratha, plain',
    serving: '1 medium',
    servingG: 60,
    kcal: 220,
    proteinG: 4.5,
    carbG: 27,
    fatG: 10.5,
    fibreG: 2.5,
    ironMg: 1.4,
    contains: ['gluten'],
    group: 'carb',
    aliases: ['flatbread', 'parantha'],
    cuisines: ['south-asian'],
  },
  {
    id: 'basmati-rice',
    name: 'Basmati rice, cooked',
    serving: '1 cup',
    servingG: 158,
    kcal: 205,
    proteinG: 4.3,
    carbG: 45,
    fatG: 0.4,
    fibreG: 0.6,
    ironMg: 1.9,
    contains: [],
    group: 'carb',
    aliases: ['white rice', 'chawal', 'plain rice'],
    cuisines: ['south-asian'],
  },
  {
    id: 'daal',
    name: 'Daal (masoor or moong)',
    serving: '1 cup',
    servingG: 200,
    kcal: 180,
    proteinG: 12,
    carbG: 27,
    fatG: 2.5,
    fibreG: 8,
    ironMg: 3.3,
    contains: [],
    group: 'protein',
    aliases: ['dal', 'dhal', 'lentils', 'lentil curry', 'moong', 'masoor'],
    cuisines: ['south-asian'],
  },
  {
    id: 'chana-masala',
    name: 'Chana masala',
    serving: '1 cup',
    servingG: 240,
    kcal: 270,
    proteinG: 12,
    carbG: 38,
    fatG: 8,
    fibreG: 10,
    ironMg: 3.2,
    contains: [],
    group: 'protein',
    aliases: ['chole', 'chickpea curry', 'garbanzo'],
    cuisines: ['south-asian'],
  },
  {
    id: 'rajma',
    name: 'Rajma (kidney bean curry)',
    serving: '1 cup',
    servingG: 240,
    kcal: 245,
    proteinG: 12,
    carbG: 35,
    fatG: 6,
    fibreG: 11,
    ironMg: 3.5,
    contains: [],
    group: 'protein',
    aliases: ['kidney beans', 'bean curry'],
    cuisines: ['south-asian'],
  },
  {
    id: 'chicken-karahi',
    name: 'Chicken karahi',
    serving: '1 cup',
    servingG: 200,
    kcal: 300,
    proteinG: 28,
    carbG: 8,
    fatG: 18,
    fibreG: 2,
    ironMg: 1.6,
    contains: ['meat'],
    group: 'protein',
    aliases: ['kadai chicken', 'chicken curry', 'salan'],
    cuisines: ['south-asian'],
  },
  {
    id: 'chicken-tikka',
    name: 'Chicken tikka',
    serving: '1 skewer',
    servingG: 150,
    kcal: 250,
    proteinG: 35,
    carbG: 4,
    fatG: 10,
    fibreG: 0,
    ironMg: 1.3,
    contains: ['meat', 'dairy'],
    group: 'protein',
    aliases: ['grilled chicken', 'tandoori'],
    cuisines: ['south-asian'],
  },
  {
    id: 'chicken-biryani',
    name: 'Chicken biryani',
    serving: '1 cup',
    servingG: 240,
    kcal: 350,
    proteinG: 18,
    carbG: 40,
    fatG: 13,
    fibreG: 2,
    ironMg: 1.8,
    contains: ['meat'],
    group: 'mixed',
    aliases: ['pulao', 'rice dish'],
    cuisines: ['south-asian'],
  },
  {
    id: 'mutton-curry',
    name: 'Mutton or beef curry',
    serving: '1 cup',
    servingG: 240,
    kcal: 330,
    proteinG: 24,
    carbG: 12,
    fatG: 20,
    fibreG: 2,
    ironMg: 3,
    contains: ['meat'],
    group: 'protein',
    aliases: ['lamb curry', 'beef curry', 'gosht'],
    cuisines: ['south-asian'],
  },
  {
    id: 'seekh-kebab',
    name: 'Seekh kebab',
    serving: '2 pieces',
    servingG: 100,
    kcal: 260,
    proteinG: 18,
    carbG: 3,
    fatG: 20,
    fibreG: 0,
    ironMg: 2,
    contains: ['meat'],
    group: 'protein',
    aliases: ['kabab', 'kofta'],
    cuisines: ['south-asian'],
  },
  {
    id: 'fish-curry',
    name: 'Fish curry',
    serving: '1 cup',
    servingG: 220,
    kcal: 240,
    proteinG: 24,
    carbG: 6,
    fatG: 13,
    fibreG: 1,
    ironMg: 1.5,
    contains: ['fish'],
    group: 'protein',
    aliases: ['machli', 'seafood curry'],
    cuisines: ['south-asian'],
  },
  {
    id: 'haleem',
    name: 'Haleem',
    serving: '1 cup',
    servingG: 240,
    kcal: 300,
    proteinG: 18,
    carbG: 30,
    fatG: 12,
    fibreG: 5,
    ironMg: 3.4,
    contains: ['meat', 'gluten'],
    group: 'mixed',
    cuisines: ['south-asian'],
  },
  {
    id: 'paneer',
    name: 'Paneer',
    serving: '100 g',
    servingG: 100,
    kcal: 296,
    proteinG: 18.3,
    carbG: 3.6,
    fatG: 22.8,
    fibreG: 0,
    ironMg: 0.2,
    contains: ['dairy'],
    group: 'protein',
    aliases: ['indian cheese'],
    cuisines: ['south-asian'],
  },
  {
    id: 'palak-paneer',
    name: 'Palak paneer',
    serving: '1 cup',
    servingG: 200,
    kcal: 270,
    proteinG: 12,
    carbG: 10,
    fatG: 20,
    fibreG: 4,
    ironMg: 2.8,
    contains: ['dairy'],
    group: 'mixed',
    aliases: ['saag paneer', 'spinach curry'],
    cuisines: ['south-asian'],
  },
  {
    id: 'aloo-sabzi',
    name: 'Aloo sabzi',
    serving: '1 cup',
    servingG: 200,
    kcal: 190,
    proteinG: 4,
    carbG: 28,
    fatG: 7,
    fibreG: 4,
    ironMg: 1.2,
    contains: [],
    group: 'carb',
    aliases: ['potato curry', 'aloo'],
    cuisines: ['south-asian'],
  },
  {
    id: 'bhindi',
    name: 'Bhindi (okra) masala',
    serving: '1 cup',
    servingG: 180,
    kcal: 150,
    proteinG: 3,
    carbG: 12,
    fatG: 10,
    fibreG: 5,
    ironMg: 0.9,
    contains: [],
    group: 'veg',
    aliases: ['okra', 'ladyfinger'],
    cuisines: ['south-asian'],
  },
  {
    id: 'mixed-sabzi',
    name: 'Mixed vegetable sabzi',
    serving: '1 cup',
    servingG: 180,
    kcal: 130,
    proteinG: 3,
    carbG: 12,
    fatG: 8,
    fibreG: 4,
    ironMg: 1.1,
    contains: [],
    group: 'veg',
    aliases: ['vegetable curry', 'sabji', 'veg'],
    cuisines: ['south-asian'],
  },
  {
    id: 'dahi',
    name: 'Dahi (plain yogurt)',
    serving: '1 cup',
    servingG: 245,
    kcal: 150,
    proteinG: 8.5,
    carbG: 11.4,
    fatG: 8,
    fibreG: 0,
    ironMg: 0.1,
    contains: ['dairy'],
    group: 'dairy',
    snack: true,
    aliases: ['yogurt', 'yoghurt', 'curd', 'plain yogurt'],
    cuisines: ['south-asian'],
  },
  {
    id: 'raita',
    name: 'Raita',
    serving: '1 cup',
    servingG: 240,
    kcal: 90,
    proteinG: 5,
    carbG: 8,
    fatG: 4,
    fibreG: 1,
    ironMg: 0.2,
    contains: ['dairy'],
    group: 'dairy',
    snack: true,
    aliases: ['yogurt salad'],
    cuisines: ['south-asian'],
  },
  {
    id: 'lassi-salted',
    name: 'Lassi, salted',
    serving: '1 glass',
    servingG: 250,
    kcal: 130,
    proteinG: 6,
    carbG: 12,
    fatG: 6,
    fibreG: 0,
    ironMg: 0.1,
    contains: ['dairy'],
    group: 'dairy',
    snack: true,
    aliases: ['chaas', 'buttermilk'],
    cuisines: ['south-asian'],
  },
  {
    id: 'chana-chaat',
    name: 'Chana chaat',
    serving: '1 cup',
    servingG: 200,
    kcal: 200,
    proteinG: 9,
    carbG: 30,
    fatG: 5,
    fibreG: 8,
    ironMg: 2.6,
    contains: [],
    group: 'mixed',
    snack: true,
    aliases: ['chickpea salad'],
    cuisines: ['south-asian'],
  },
  {
    id: 'roasted-chana',
    name: 'Roasted chana',
    serving: 'small handful',
    servingG: 30,
    kcal: 120,
    proteinG: 6,
    carbG: 18,
    fatG: 2,
    fibreG: 5,
    ironMg: 1.4,
    contains: [],
    group: 'protein',
    snack: true,
    aliases: ['roasted chickpeas'],
    cuisines: ['south-asian'],
  },
  {
    id: 'samosa',
    name: 'Samosa',
    serving: '1',
    servingG: 60,
    kcal: 200,
    proteinG: 4,
    carbG: 22,
    fatG: 11,
    fibreG: 2,
    ironMg: 0.9,
    contains: ['gluten'],
    group: 'mixed',
    snack: true,
    cuisines: ['south-asian'],
  },
  {
    id: 'pakora',
    name: 'Pakora',
    serving: '5-6 pieces',
    servingG: 100,
    kcal: 315,
    proteinG: 8,
    carbG: 30,
    fatG: 18,
    fibreG: 4,
    ironMg: 2.1,
    contains: [],
    group: 'mixed',
    snack: true,
    cuisines: ['south-asian'],
  },

  /* ------------------------------- protein ------------------------------- */
  {
    id: 'chicken-breast',
    name: 'Chicken breast, cooked',
    serving: '100 g',
    servingG: 100,
    kcal: 165,
    proteinG: 31,
    carbG: 0,
    fatG: 3.6,
    fibreG: 0,
    ironMg: 1,
    contains: ['meat'],
    group: 'protein',
    aliases: ['chicken', 'grilled chicken', 'poultry'],
  },
  {
    id: 'beef-mince-lean',
    name: 'Lean beef mince, cooked',
    serving: '100 g',
    servingG: 100,
    kcal: 215,
    proteinG: 26,
    carbG: 0,
    fatG: 12,
    fibreG: 0,
    ironMg: 2.6,
    contains: ['meat'],
    group: 'protein',
    aliases: ['ground beef', 'keema', 'mince'],
  },
  {
    id: 'egg-boiled',
    name: 'Egg, boiled',
    serving: '1 large',
    servingG: 50,
    kcal: 78,
    proteinG: 6.3,
    carbG: 0.6,
    fatG: 5.3,
    fibreG: 0,
    ironMg: 0.9,
    contains: ['egg'],
    group: 'protein',
    snack: true,
    aliases: ['eggs', 'anda', 'hard boiled egg'],
  },
  {
    id: 'tuna-canned',
    name: 'Tuna, canned in water',
    serving: '1 tin, drained',
    servingG: 100,
    kcal: 116,
    proteinG: 26,
    carbG: 0,
    fatG: 1,
    fibreG: 0,
    ironMg: 1.3,
    contains: ['fish'],
    group: 'protein',
    snack: true,
    aliases: ['tinned tuna', 'fish'],
  },
  {
    id: 'salmon',
    name: 'Salmon, cooked',
    serving: '1 fillet',
    servingG: 100,
    kcal: 208,
    proteinG: 22,
    carbG: 0,
    fatG: 13,
    fibreG: 0,
    ironMg: 0.3,
    contains: ['fish'],
    group: 'protein',
    aliases: ['fish', 'oily fish'],
  },
  {
    id: 'greek-yogurt',
    name: 'Greek yogurt, plain',
    serving: '1 pot',
    servingG: 170,
    kcal: 100,
    proteinG: 17,
    carbG: 6,
    fatG: 0.7,
    fibreG: 0,
    ironMg: 0.1,
    contains: ['dairy'],
    group: 'dairy',
    snack: true,
    aliases: ['yoghurt', 'high protein yogurt', 'skyr'],
  },
  {
    id: 'cottage-cheese',
    name: 'Cottage cheese',
    serving: '100 g',
    servingG: 100,
    kcal: 98,
    proteinG: 11,
    carbG: 3.4,
    fatG: 4.3,
    fibreG: 0,
    ironMg: 0.1,
    contains: ['dairy'],
    group: 'dairy',
    snack: true,
    aliases: ['curd cheese'],
  },
  {
    id: 'tofu-firm',
    name: 'Firm tofu',
    serving: '100 g',
    servingG: 100,
    kcal: 144,
    proteinG: 17,
    carbG: 3,
    fatG: 9,
    fibreG: 2,
    ironMg: 2.7,
    contains: ['soy'],
    group: 'protein',
    aliases: ['bean curd', 'soya'],
  },
  {
    id: 'chickpeas',
    name: 'Chickpeas, boiled',
    serving: '1 cup',
    servingG: 164,
    kcal: 269,
    proteinG: 14.5,
    carbG: 45,
    fatG: 4.2,
    fibreG: 12.5,
    ironMg: 4.7,
    contains: [],
    group: 'protein',
    aliases: ['garbanzo beans', 'chana', 'kabuli'],
  },
  {
    id: 'whey-scoop',
    name: 'Whey protein',
    serving: '1 scoop',
    servingG: 30,
    kcal: 120,
    proteinG: 24,
    carbG: 3,
    fatG: 1.5,
    fibreG: 0,
    ironMg: 0.3,
    contains: ['dairy'],
    group: 'protein',
    snack: true,
    supplement: true,
    aliases: ['protein powder', 'protein shake', 'supplement', 'shake'],
  },
  /*
   * The other things with calories that come in a tub or a wrapper. Asked
   * for in testing. They carry the `supplement` flag like whey: searchable,
   * offered for a protein gap, never the anchor of a meal. Vitamins and
   * minerals are not here - they have no calories to count and live in the
   * supplements checklist instead.
   */
  {
    id: 'plant-protein-scoop',
    name: 'Plant protein powder',
    serving: '1 scoop',
    servingG: 30,
    kcal: 115,
    proteinG: 21,
    carbG: 4,
    fatG: 2,
    fibreG: 1.5,
    ironMg: 4.5,
    contains: ['soy'],
    group: 'protein',
    snack: true,
    supplement: true,
    aliases: ['pea protein', 'vegan protein', 'soy protein', 'protein powder', 'supplement', 'shake'],
  },
  {
    id: 'protein-bar',
    name: 'Protein bar',
    serving: '1 bar',
    servingG: 60,
    kcal: 220,
    proteinG: 20,
    carbG: 22,
    fatG: 7,
    fibreG: 4,
    ironMg: 1.5,
    contains: ['dairy', 'nuts', 'soy'],
    group: 'protein',
    snack: true,
    supplement: true,
    aliases: ['bar', 'supplement'],
  },
  {
    id: 'mass-gainer-scoop',
    name: 'Mass gainer shake',
    serving: '1 serving',
    servingG: 100,
    kcal: 380,
    proteinG: 25,
    carbG: 60,
    fatG: 4,
    fibreG: 1,
    ironMg: 1,
    contains: ['dairy'],
    group: 'mixed',
    supplement: true,
    aliases: ['weight gainer', 'gainer', 'supplement', 'shake'],
  },
  {
    id: 'electrolyte-drink',
    name: 'Electrolyte / sports drink',
    serving: '1 bottle (500 ml)',
    servingG: 500,
    kcal: 120,
    proteinG: 0,
    carbG: 30,
    fatG: 0,
    fibreG: 0,
    ironMg: 0,
    contains: [],
    group: 'carb',
    supplement: true,
    aliases: ['sports drink', 'ors', 'rehydration', 'gatorade', 'supplement'],
  },

  /* -------------------------------- carbs -------------------------------- */
  {
    id: 'oats',
    name: 'Oats, dry',
    serving: '40 g',
    servingG: 40,
    kcal: 150,
    proteinG: 5,
    carbG: 27,
    fatG: 3,
    fibreG: 4,
    ironMg: 1.7,
    contains: ['gluten'],
    group: 'carb',
    aliases: ['porridge', 'oatmeal', 'dalia'],
  },
  {
    id: 'wholemeal-bread',
    name: 'Wholemeal bread',
    serving: '1 slice',
    servingG: 40,
    kcal: 92,
    proteinG: 4,
    carbG: 16,
    fatG: 1.2,
    fibreG: 2.4,
    ironMg: 1,
    contains: ['gluten'],
    group: 'carb',
    aliases: ['brown bread', 'toast', 'wholewheat bread'],
  },
  {
    id: 'brown-rice',
    name: 'Brown rice, cooked',
    serving: '1 cup',
    servingG: 195,
    kcal: 218,
    proteinG: 5,
    carbG: 46,
    fatG: 1.6,
    fibreG: 3.5,
    ironMg: 1.1,
    contains: [],
    group: 'carb',
    aliases: ['whole grain rice'],
  },
  {
    id: 'sweet-potato',
    name: 'Sweet potato, baked',
    serving: '1 medium',
    servingG: 130,
    kcal: 112,
    proteinG: 2,
    carbG: 26,
    fatG: 0.1,
    fibreG: 3.9,
    ironMg: 0.8,
    contains: [],
    group: 'carb',
    aliases: ['yam', 'shakarkandi'],
  },

  /* ---------------------------- veg and fruit ---------------------------- */
  {
    id: 'spinach-cooked',
    name: 'Spinach, cooked',
    serving: '1 cup',
    servingG: 180,
    kcal: 41,
    proteinG: 5.3,
    carbG: 6.8,
    fatG: 0.5,
    fibreG: 4.3,
    ironMg: 6.4,
    contains: [],
    group: 'veg',
    aliases: ['palak', 'saag', 'greens'],
  },
  {
    id: 'salad',
    name: 'Green salad, undressed',
    serving: '1 bowl',
    servingG: 100,
    kcal: 25,
    proteinG: 1.5,
    carbG: 4,
    fatG: 0.3,
    fibreG: 2,
    ironMg: 0.8,
    contains: [],
    group: 'veg',
    aliases: ['greens', 'lettuce', 'raw vegetables'],
  },
  {
    id: 'banana',
    name: 'Banana',
    serving: '1 medium',
    servingG: 118,
    kcal: 105,
    proteinG: 1.3,
    carbG: 27,
    fatG: 0.4,
    fibreG: 3.1,
    ironMg: 0.3,
    contains: [],
    group: 'fruit',
    snack: true,
    aliases: ['kela'],
  },
  {
    id: 'apple',
    name: 'Apple',
    serving: '1 medium',
    servingG: 182,
    kcal: 95,
    proteinG: 0.5,
    carbG: 25,
    fatG: 0.3,
    fibreG: 4.4,
    ironMg: 0.2,
    contains: [],
    group: 'fruit',
    snack: true,
    aliases: ['seb'],
  },
  {
    id: 'dates',
    name: 'Dates',
    serving: '3',
    servingG: 24,
    kcal: 66,
    proteinG: 0.6,
    carbG: 18,
    fatG: 0,
    fibreG: 1.6,
    ironMg: 0.2,
    contains: [],
    group: 'fruit',
    snack: true,
    aliases: ['khajoor', 'khajur'],
    cuisines: ['south-asian', 'middle-eastern', 'african'],
  },

  /* ------------------------------ fats etc ------------------------------ */
  {
    id: 'almonds',
    name: 'Almonds',
    serving: 'small handful',
    servingG: 28,
    kcal: 164,
    proteinG: 6,
    carbG: 6,
    fatG: 14,
    fibreG: 3.5,
    ironMg: 1.1,
    contains: ['nuts'],
    group: 'fat',
    snack: true,
    aliases: ['badam', 'nuts'],
  },
  {
    id: 'peanuts',
    name: 'Peanuts',
    serving: 'small handful',
    servingG: 30,
    kcal: 170,
    proteinG: 7,
    carbG: 5,
    fatG: 15,
    fibreG: 2.5,
    ironMg: 1.4,
    contains: ['nuts'],
    group: 'fat',
    snack: true,
    aliases: ['groundnuts', 'moongphali', 'nuts'],
  },
  {
    id: 'olive-oil',
    name: 'Olive oil',
    serving: '1 tbsp',
    servingG: 14,
    kcal: 119,
    proteinG: 0,
    carbG: 0,
    fatG: 13.5,
    fibreG: 0,
    ironMg: 0,
    contains: [],
    group: 'fat',
    aliases: ['cooking oil', 'oil'],
  },
  {
    id: 'ghee',
    name: 'Ghee',
    serving: '1 tsp',
    servingG: 5,
    kcal: 45,
    proteinG: 0,
    carbG: 0,
    fatG: 5,
    fibreG: 0,
    ironMg: 0,
    contains: ['dairy'],
    group: 'fat',
    aliases: ['clarified butter', 'butter'],
    cuisines: ['south-asian'],
  },
  {
    id: 'milk-full',
    name: 'Milk, full fat',
    serving: '1 glass',
    servingG: 250,
    kcal: 150,
    proteinG: 8,
    carbG: 12,
    fatG: 8,
    fibreG: 0,
    ironMg: 0.1,
    contains: ['dairy'],
    group: 'dairy',
    snack: true,
    aliases: ['whole milk', 'doodh'],
  },
  {
    id: 'milk-skim',
    name: 'Milk, semi-skimmed',
    serving: '1 glass',
    servingG: 250,
    kcal: 105,
    proteinG: 8.5,
    carbG: 12,
    fatG: 2.4,
    fibreG: 0,
    ironMg: 0.1,
    contains: ['dairy'],
    group: 'dairy',
    snack: true,
    aliases: ['semi skimmed milk', 'low fat milk', 'doodh'],
  },
  /* --------------------------- Middle Eastern --------------------------- */
  {
    id: 'hummus',
    name: 'Hummus',
    serving: 'half a cup',
    servingG: 120,
    kcal: 200,
    proteinG: 6,
    carbG: 18,
    fatG: 12,
    fibreG: 5,
    ironMg: 1.7,
    contains: [],
    group: 'protein',
    snack: true,
    aliases: ['houmous', 'chickpea dip'],
    cuisines: ['middle-eastern', 'mediterranean'],
  },
  {
    id: 'pita-bread',
    name: 'Pita bread',
    serving: '1 pocket',
    servingG: 60,
    kcal: 165,
    proteinG: 5.5,
    carbG: 33,
    fatG: 0.7,
    fibreG: 1.3,
    ironMg: 1.6,
    contains: ['gluten'],
    group: 'carb',
    aliases: ['khubz', 'flatbread', 'pitta'],
    cuisines: ['middle-eastern', 'mediterranean'],
  },
  {
    id: 'falafel',
    name: 'Falafel',
    serving: '4 pieces',
    servingG: 70,
    kcal: 230,
    proteinG: 9,
    carbG: 21,
    fatG: 12,
    fibreG: 5,
    ironMg: 2.3,
    contains: [],
    group: 'protein',
    aliases: ['chickpea fritters'],
    cuisines: ['middle-eastern'],
  },
  {
    id: 'chicken-shawarma',
    name: 'Chicken shawarma',
    serving: '1 cup of meat',
    servingG: 150,
    kcal: 280,
    proteinG: 32,
    carbG: 4,
    fatG: 15,
    fibreG: 0.5,
    ironMg: 1.6,
    contains: ['meat'],
    group: 'protein',
    aliases: ['doner', 'grilled chicken'],
    cuisines: ['middle-eastern'],
  },
  {
    id: 'lamb-kofta',
    name: 'Lamb kofta',
    serving: '2 skewers',
    servingG: 110,
    kcal: 290,
    proteinG: 20,
    carbG: 3,
    fatG: 22,
    fibreG: 0.5,
    ironMg: 2.2,
    contains: ['meat'],
    group: 'protein',
    aliases: ['kebab', 'kofte', 'meatballs'],
    cuisines: ['middle-eastern'],
  },
  {
    id: 'labneh',
    name: 'Labneh',
    serving: '100 g',
    servingG: 100,
    kcal: 155,
    proteinG: 8,
    carbG: 6,
    fatG: 11,
    fibreG: 0,
    ironMg: 0.1,
    contains: ['dairy'],
    group: 'dairy',
    snack: true,
    aliases: ['strained yogurt', 'yoghurt cheese'],
    cuisines: ['middle-eastern'],
  },
  {
    id: 'tabbouleh',
    name: 'Tabbouleh',
    serving: '1 cup',
    servingG: 150,
    kcal: 120,
    proteinG: 3,
    carbG: 13,
    fatG: 7,
    fibreG: 3,
    ironMg: 1.4,
    contains: ['gluten'],
    group: 'veg',
    aliases: ['parsley salad', 'bulgur salad'],
    cuisines: ['middle-eastern', 'mediterranean'],
  },
  {
    id: 'mujadara',
    name: 'Mujadara (lentils and rice)',
    serving: '1 cup',
    servingG: 200,
    kcal: 290,
    proteinG: 10,
    carbG: 45,
    fatG: 8,
    fibreG: 7,
    ironMg: 3.2,
    contains: [],
    group: 'mixed',
    aliases: ['lentil rice', 'mjadra'],
    cuisines: ['middle-eastern'],
  },
  {
    id: 'foul-medames',
    name: 'Foul medames (fava beans)',
    serving: '1 cup',
    servingG: 200,
    kcal: 220,
    proteinG: 13,
    carbG: 30,
    fatG: 5,
    fibreG: 11,
    ironMg: 3.9,
    contains: [],
    group: 'protein',
    aliases: ['ful', 'fava beans', 'broad beans'],
    cuisines: ['middle-eastern', 'african'],
  },
  {
    id: 'baba-ganoush',
    name: 'Baba ganoush',
    serving: 'half a cup',
    servingG: 100,
    kcal: 130,
    proteinG: 3,
    carbG: 9,
    fatG: 10,
    fibreG: 4,
    ironMg: 0.7,
    contains: [],
    group: 'veg',
    snack: true,
    aliases: ['aubergine dip', 'eggplant dip'],
    cuisines: ['middle-eastern'],
  },
  {
    id: 'halloumi',
    name: 'Halloumi, grilled',
    serving: '60 g',
    servingG: 60,
    kcal: 190,
    proteinG: 13,
    carbG: 1.5,
    fatG: 15,
    fibreG: 0,
    ironMg: 0.2,
    contains: ['dairy'],
    group: 'dairy',
    snack: true,
    aliases: ['grilling cheese'],
    cuisines: ['middle-eastern', 'mediterranean'],
  },
  {
    id: 'shakshuka',
    name: 'Shakshuka',
    serving: '1 pan',
    servingG: 300,
    kcal: 280,
    proteinG: 16,
    carbG: 14,
    fatG: 18,
    fibreG: 4,
    ironMg: 3,
    contains: ['egg'],
    group: 'protein',
    aliases: ['eggs in tomato', 'menemen'],
    cuisines: ['middle-eastern', 'mediterranean'],
  },

  /* ------------------------------ East Asian ------------------------------ */
  {
    id: 'white-rice',
    name: 'White rice, cooked',
    serving: '1 cup',
    servingG: 158,
    kcal: 205,
    proteinG: 4.3,
    carbG: 45,
    fatG: 0.4,
    fibreG: 0.6,
    ironMg: 1.9,
    contains: [],
    group: 'carb',
    aliases: ['steamed rice', 'jasmine rice', 'plain rice'],
    cuisines: [
      'east-asian',
      'southeast-asian',
      'latin-american',
      'african',
      'middle-eastern',
    ],
  },
  {
    id: 'miso-soup',
    name: 'Miso soup',
    serving: '1 bowl',
    servingG: 240,
    kcal: 60,
    proteinG: 4,
    carbG: 6,
    fatG: 2,
    fibreG: 1,
    ironMg: 0.6,
    contains: ['soy'],
    group: 'veg',
    snack: true,
    aliases: ['soup'],
    cuisines: ['east-asian'],
  },
  {
    id: 'edamame',
    name: 'Edamame, shelled',
    serving: '1 cup',
    servingG: 155,
    kcal: 190,
    proteinG: 18,
    carbG: 14,
    fatG: 8,
    fibreG: 8,
    ironMg: 3.5,
    contains: ['soy'],
    group: 'protein',
    snack: true,
    aliases: ['soy beans', 'green soybeans'],
    cuisines: ['east-asian'],
  },
  {
    id: 'chicken-stir-fry',
    name: 'Chicken and vegetable stir fry',
    serving: '1 cup',
    servingG: 250,
    kcal: 300,
    proteinG: 28,
    carbG: 15,
    fatG: 14,
    fibreG: 3,
    ironMg: 1.8,
    contains: ['meat', 'soy'],
    group: 'protein',
    aliases: ['stirfry', 'wok chicken'],
    cuisines: ['east-asian', 'southeast-asian'],
  },
  {
    id: 'kimchi',
    name: 'Kimchi',
    serving: 'half a cup',
    servingG: 75,
    kcal: 20,
    proteinG: 1,
    carbG: 3,
    fatG: 0.3,
    fibreG: 1.5,
    ironMg: 0.4,
    contains: [],
    group: 'veg',
    snack: true,
    aliases: ['pickled cabbage'],
    cuisines: ['east-asian'],
  },
  {
    id: 'sushi-salmon',
    name: 'Salmon sushi',
    serving: '6 pieces',
    servingG: 180,
    kcal: 300,
    proteinG: 16,
    carbG: 42,
    fatG: 7,
    fibreG: 2,
    ironMg: 1,
    contains: ['fish'],
    group: 'mixed',
    aliases: ['maki', 'nigiri'],
    cuisines: ['east-asian'],
  },
  {
    id: 'ramen-noodles',
    name: 'Ramen with broth',
    serving: '1 bowl',
    servingG: 400,
    kcal: 450,
    proteinG: 22,
    carbG: 60,
    fatG: 14,
    fibreG: 4,
    ironMg: 3,
    contains: ['gluten', 'soy', 'meat'],
    group: 'mixed',
    aliases: ['noodle soup', 'noodles'],
    cuisines: ['east-asian'],
  },
  {
    id: 'egg-fried-rice',
    name: 'Egg fried rice',
    serving: '1 cup',
    servingG: 200,
    kcal: 330,
    proteinG: 11,
    carbG: 45,
    fatG: 12,
    fibreG: 2,
    ironMg: 1.5,
    contains: ['egg', 'soy'],
    group: 'mixed',
    aliases: ['fried rice'],
    cuisines: ['east-asian'],
  },
  {
    id: 'steamed-fish-ginger',
    name: 'Steamed fish with ginger',
    serving: '1 fillet',
    servingG: 150,
    kcal: 190,
    proteinG: 27,
    carbG: 2,
    fatG: 8,
    fibreG: 0,
    ironMg: 0.6,
    contains: ['fish', 'soy'],
    group: 'protein',
    aliases: ['steamed fish'],
    cuisines: ['east-asian'],
  },
  {
    id: 'bok-choy',
    name: 'Bok choy, cooked',
    serving: '1 cup',
    servingG: 170,
    kcal: 40,
    proteinG: 2.7,
    carbG: 3,
    fatG: 2,
    fibreG: 1.7,
    ironMg: 1.8,
    contains: [],
    group: 'veg',
    aliases: ['pak choi', 'chinese cabbage', 'greens'],
    cuisines: ['east-asian'],
  },

  /* --------------------------- Southeast Asian --------------------------- */
  {
    id: 'chicken-adobo',
    name: 'Chicken adobo',
    serving: '1 cup',
    servingG: 200,
    kcal: 320,
    proteinG: 28,
    carbG: 6,
    fatG: 20,
    fibreG: 0.5,
    ironMg: 1.8,
    contains: ['meat', 'soy'],
    group: 'protein',
    aliases: ['adobo', 'braised chicken'],
    cuisines: ['southeast-asian'],
  },
  {
    id: 'pho-beef',
    name: 'Pho with beef',
    serving: '1 bowl',
    servingG: 500,
    kcal: 380,
    proteinG: 25,
    carbG: 45,
    fatG: 10,
    fibreG: 2,
    ironMg: 3.2,
    contains: ['meat'],
    group: 'mixed',
    aliases: ['noodle soup', 'pho bo'],
    cuisines: ['southeast-asian'],
  },
  {
    id: 'nasi-goreng',
    name: 'Nasi goreng',
    serving: '1 cup',
    servingG: 220,
    kcal: 350,
    proteinG: 12,
    carbG: 45,
    fatG: 14,
    fibreG: 2,
    ironMg: 1.6,
    contains: ['egg', 'soy'],
    group: 'mixed',
    aliases: ['fried rice'],
    cuisines: ['southeast-asian'],
  },
  {
    id: 'thai-green-curry',
    name: 'Thai green curry with chicken',
    serving: '1 cup',
    servingG: 240,
    kcal: 300,
    proteinG: 22,
    carbG: 10,
    fatG: 19,
    fibreG: 2,
    ironMg: 1.5,
    contains: ['meat', 'fish'],
    group: 'protein',
    aliases: ['green curry', 'coconut curry'],
    cuisines: ['southeast-asian'],
  },
  {
    id: 'tempeh',
    name: 'Tempeh',
    serving: '100 g',
    servingG: 100,
    kcal: 195,
    proteinG: 19,
    carbG: 8,
    fatG: 11,
    fibreG: 5,
    ironMg: 2.7,
    contains: ['soy'],
    group: 'protein',
    snack: true,
    aliases: ['fermented soy'],
    cuisines: ['southeast-asian'],
  },
  {
    id: 'satay-chicken',
    name: 'Chicken satay',
    serving: '3 skewers',
    servingG: 120,
    kcal: 250,
    proteinG: 26,
    carbG: 6,
    fatG: 13,
    fibreG: 1,
    ironMg: 1.2,
    contains: ['meat', 'nuts', 'soy'],
    group: 'protein',
    aliases: ['sate', 'grilled chicken skewers'],
    cuisines: ['southeast-asian'],
  },
  {
    id: 'rice-noodles',
    name: 'Rice noodles, cooked',
    serving: '1 cup',
    servingG: 176,
    kcal: 190,
    proteinG: 3,
    carbG: 42,
    fatG: 0.4,
    fibreG: 1.8,
    ironMg: 0.4,
    contains: [],
    group: 'carb',
    aliases: ['vermicelli', 'noodles', 'bihun'],
    cuisines: ['southeast-asian', 'east-asian'],
  },
  {
    id: 'fish-sinigang',
    name: 'Sinigang with fish',
    serving: '1 bowl',
    servingG: 300,
    kcal: 220,
    proteinG: 24,
    carbG: 12,
    fatG: 8,
    fibreG: 2,
    ironMg: 1.5,
    contains: ['fish'],
    group: 'protein',
    aliases: ['sour soup', 'fish soup'],
    cuisines: ['southeast-asian'],
  },
  {
    id: 'gado-gado',
    name: 'Gado-gado',
    serving: '1 plate',
    servingG: 250,
    kcal: 330,
    proteinG: 13,
    carbG: 24,
    fatG: 21,
    fibreG: 6,
    ironMg: 2.5,
    contains: ['nuts', 'egg', 'soy'],
    group: 'mixed',
    aliases: ['peanut salad', 'vegetable salad'],
    cuisines: ['southeast-asian'],
  },

  /* ----------------------------- Mediterranean ----------------------------- */
  {
    id: 'greek-salad',
    name: 'Greek salad',
    serving: '1 bowl',
    servingG: 250,
    kcal: 230,
    proteinG: 7,
    carbG: 10,
    fatG: 18,
    fibreG: 3,
    ironMg: 1.1,
    contains: ['dairy'],
    group: 'veg',
    aliases: ['horiatiki', 'salad'],
    cuisines: ['mediterranean'],
  },
  {
    id: 'grilled-sardines',
    name: 'Sardines, grilled',
    serving: '100 g',
    servingG: 100,
    kcal: 208,
    proteinG: 25,
    carbG: 0,
    fatG: 12,
    fibreG: 0,
    ironMg: 2.9,
    contains: ['fish'],
    group: 'protein',
    aliases: ['tinned sardines', 'oily fish'],
    cuisines: ['mediterranean'],
  },
  {
    id: 'wholewheat-pasta',
    name: 'Wholewheat pasta, cooked',
    serving: '1 cup',
    servingG: 140,
    kcal: 175,
    proteinG: 7.5,
    carbG: 37,
    fatG: 0.8,
    fibreG: 4.5,
    ironMg: 1.5,
    contains: ['gluten'],
    group: 'carb',
    aliases: ['spaghetti', 'penne', 'macaroni', 'noodles'],
    cuisines: ['mediterranean', 'western'],
  },
  {
    id: 'lentil-soup',
    name: 'Lentil soup',
    serving: '1 bowl',
    servingG: 250,
    kcal: 190,
    proteinG: 12,
    carbG: 28,
    fatG: 3,
    fibreG: 8,
    ironMg: 3.3,
    contains: [],
    group: 'protein',
    aliases: ['lentils', 'soup', 'fakes'],
    cuisines: ['mediterranean', 'middle-eastern'],
  },
  {
    id: 'feta',
    name: 'Feta',
    serving: '50 g',
    servingG: 50,
    kcal: 132,
    proteinG: 7,
    carbG: 2,
    fatG: 11,
    fibreG: 0,
    ironMg: 0.3,
    contains: ['dairy'],
    group: 'dairy',
    snack: true,
    aliases: ['white cheese'],
    cuisines: ['mediterranean'],
  },
  {
    id: 'chicken-souvlaki',
    name: 'Chicken souvlaki',
    serving: '1 skewer',
    servingG: 120,
    kcal: 220,
    proteinG: 28,
    carbG: 2,
    fatG: 11,
    fibreG: 0,
    ironMg: 1.1,
    contains: ['meat'],
    group: 'protein',
    aliases: ['grilled chicken skewer', 'gyros'],
    cuisines: ['mediterranean'],
  },
  {
    id: 'white-beans-tomato',
    name: 'White beans in tomato',
    serving: '1 cup',
    servingG: 250,
    kcal: 250,
    proteinG: 14,
    carbG: 38,
    fatG: 4,
    fibreG: 10,
    ironMg: 4.2,
    contains: [],
    group: 'protein',
    aliases: ['cannellini', 'butter beans', 'gigantes'],
    cuisines: ['mediterranean'],
  },
  {
    id: 'olives',
    name: 'Olives',
    serving: '10 olives',
    servingG: 40,
    kcal: 60,
    proteinG: 0.4,
    carbG: 1.5,
    fatG: 6,
    fibreG: 1.2,
    ironMg: 1.3,
    contains: [],
    group: 'fat',
    snack: true,
    aliases: ['zaytoon'],
    cuisines: ['mediterranean', 'middle-eastern'],
  },

  /* -------------------------------- Western -------------------------------- */
  {
    id: 'scrambled-eggs',
    name: 'Scrambled eggs',
    serving: '2 eggs',
    servingG: 120,
    kcal: 200,
    proteinG: 13,
    carbG: 2,
    fatG: 15,
    fibreG: 0,
    ironMg: 1.8,
    contains: ['egg', 'dairy'],
    group: 'protein',
    aliases: ['eggs', 'omelette'],
    cuisines: ['western'],
  },
  {
    id: 'baked-potato',
    name: 'Baked potato',
    serving: '1 medium',
    servingG: 175,
    kcal: 160,
    proteinG: 4.3,
    carbG: 37,
    fatG: 0.2,
    fibreG: 3.8,
    ironMg: 1.9,
    contains: [],
    group: 'carb',
    aliases: ['jacket potato', 'potato', 'aloo'],
    cuisines: ['western'],
  },
  {
    id: 'grilled-steak',
    name: 'Steak, grilled',
    serving: '100 g',
    servingG: 100,
    kcal: 250,
    proteinG: 27,
    carbG: 0,
    fatG: 16,
    fibreG: 0,
    ironMg: 2.6,
    contains: ['meat'],
    group: 'protein',
    aliases: ['beef', 'sirloin'],
    cuisines: ['western', 'latin-american'],
  },
  {
    id: 'baked-beans',
    name: 'Baked beans',
    serving: 'half a tin',
    servingG: 200,
    kcal: 155,
    proteinG: 9,
    carbG: 26,
    fatG: 1,
    fibreG: 7,
    ironMg: 2.4,
    contains: [],
    group: 'protein',
    snack: true,
    aliases: ['beans on toast', 'haricot beans'],
    cuisines: ['western'],
  },
  {
    id: 'cheddar',
    name: 'Cheddar',
    serving: '30 g',
    servingG: 30,
    kcal: 120,
    proteinG: 7,
    carbG: 0.4,
    fatG: 10,
    fibreG: 0,
    ironMg: 0.1,
    contains: ['dairy'],
    group: 'dairy',
    snack: true,
    aliases: ['cheese'],
    cuisines: ['western'],
  },
  {
    id: 'turkey-mince',
    name: 'Turkey mince, cooked',
    serving: '100 g',
    servingG: 100,
    kcal: 180,
    proteinG: 27,
    carbG: 0,
    fatG: 8,
    fibreG: 0,
    ironMg: 1.4,
    contains: ['meat'],
    group: 'protein',
    aliases: ['ground turkey', 'mince'],
    cuisines: ['western'],
  },
  {
    id: 'peanut-butter',
    name: 'Peanut butter',
    serving: '1 tbsp',
    servingG: 16,
    kcal: 95,
    proteinG: 4,
    carbG: 3,
    fatG: 8,
    fibreG: 1,
    ironMg: 0.3,
    contains: ['nuts'],
    group: 'fat',
    snack: true,
    aliases: ['nut butter'],
    cuisines: ['western'],
  },
  {
    id: 'roast-chicken-thigh',
    name: 'Roast chicken thigh',
    serving: '1 thigh',
    servingG: 110,
    kcal: 230,
    proteinG: 25,
    carbG: 0,
    fatG: 14,
    fibreG: 0,
    ironMg: 1.2,
    contains: ['meat'],
    group: 'protein',
    aliases: ['chicken', 'dark meat'],
    cuisines: ['western'],
  },
  {
    id: 'broccoli',
    name: 'Broccoli, cooked',
    serving: '1 cup',
    servingG: 156,
    kcal: 55,
    proteinG: 3.7,
    carbG: 11,
    fatG: 0.6,
    fibreG: 5,
    ironMg: 1,
    contains: [],
    group: 'veg',
    aliases: ['greens', 'vegetables'],
    cuisines: ['western'],
  },

  /* -------------------------------- African -------------------------------- */
  {
    id: 'jollof-rice',
    name: 'Jollof rice',
    serving: '1 cup',
    servingG: 200,
    kcal: 320,
    proteinG: 6,
    carbG: 50,
    fatG: 11,
    fibreG: 2,
    ironMg: 1.6,
    contains: [],
    group: 'carb',
    aliases: ['party rice', 'tomato rice'],
    cuisines: ['african'],
  },
  {
    id: 'egusi-soup',
    name: 'Egusi soup',
    serving: '1 cup',
    servingG: 200,
    kcal: 340,
    proteinG: 16,
    carbG: 8,
    fatG: 27,
    fibreG: 3,
    ironMg: 3,
    contains: ['fish'],
    group: 'protein',
    aliases: ['melon seed soup', 'stew'],
    cuisines: ['african'],
  },
  {
    id: 'injera',
    name: 'Injera',
    serving: '1 piece',
    servingG: 100,
    kcal: 165,
    proteinG: 5,
    carbG: 34,
    fatG: 1,
    fibreG: 4,
    ironMg: 2,
    contains: [],
    group: 'carb',
    aliases: ['teff flatbread', 'flatbread'],
    cuisines: ['african'],
  },
  {
    id: 'shiro-wat',
    name: 'Shiro wat',
    serving: '1 cup',
    servingG: 200,
    kcal: 260,
    proteinG: 13,
    carbG: 30,
    fatG: 10,
    fibreG: 8,
    ironMg: 4,
    contains: [],
    group: 'protein',
    aliases: ['chickpea stew', 'shiro'],
    cuisines: ['african'],
  },
  {
    id: 'ugali',
    name: 'Ugali / pap',
    serving: '1 cup',
    servingG: 200,
    kcal: 260,
    proteinG: 6,
    carbG: 56,
    fatG: 1,
    fibreG: 3,
    ironMg: 1.2,
    contains: [],
    group: 'carb',
    aliases: ['sadza', 'nsima', 'maize meal', 'fufu'],
    cuisines: ['african'],
  },
  {
    id: 'sukuma-wiki',
    name: 'Sukuma wiki (greens)',
    serving: '1 cup',
    servingG: 150,
    kcal: 110,
    proteinG: 4,
    carbG: 8,
    fatG: 7,
    fibreG: 3,
    ironMg: 1.5,
    contains: [],
    group: 'veg',
    aliases: ['collard greens', 'kale', 'greens'],
    cuisines: ['african'],
  },
  {
    id: 'plantain-fried',
    name: 'Plantain, fried',
    serving: '1 cup',
    servingG: 150,
    kcal: 280,
    proteinG: 2,
    carbG: 45,
    fatG: 11,
    fibreG: 3,
    ironMg: 0.9,
    contains: [],
    group: 'carb',
    snack: true,
    aliases: ['dodo', 'banana fritters'],
    cuisines: ['african', 'latin-american'],
  },
  {
    id: 'grilled-tilapia',
    name: 'Tilapia, grilled',
    serving: '1 fillet',
    servingG: 120,
    kcal: 155,
    proteinG: 30,
    carbG: 0,
    fatG: 3,
    fibreG: 0,
    ironMg: 0.8,
    contains: ['fish'],
    group: 'protein',
    aliases: ['fish', 'white fish'],
    cuisines: ['african'],
  },
  {
    id: 'chicken-tomato-stew',
    name: 'Chicken stew, tomato base',
    serving: '1 cup',
    servingG: 240,
    kcal: 290,
    proteinG: 26,
    carbG: 10,
    fatG: 16,
    fibreG: 2,
    ironMg: 2.2,
    contains: ['meat'],
    group: 'protein',
    aliases: ['stew', 'chicken curry', 'obe ata'],
    cuisines: ['african'],
  },
  {
    id: 'black-eyed-peas',
    name: 'Black-eyed peas',
    serving: '1 cup',
    servingG: 170,
    kcal: 200,
    proteinG: 13,
    carbG: 36,
    fatG: 1,
    fibreG: 11,
    ironMg: 4.3,
    contains: [],
    group: 'protein',
    snack: true,
    aliases: ['cowpeas', 'beans', 'lobia'],
    cuisines: ['african', 'south-asian'],
  },

  /* ----------------------------- Latin American ----------------------------- */
  {
    id: 'black-beans',
    name: 'Black beans, boiled',
    serving: '1 cup',
    servingG: 172,
    kcal: 227,
    proteinG: 15,
    carbG: 41,
    fatG: 0.9,
    fibreG: 15,
    ironMg: 3.6,
    contains: [],
    group: 'protein',
    aliases: ['frijoles', 'beans'],
    cuisines: ['latin-american'],
  },
  {
    id: 'corn-tortilla',
    name: 'Corn tortillas',
    serving: '2 pieces',
    servingG: 50,
    kcal: 110,
    proteinG: 3,
    carbG: 22,
    fatG: 1.5,
    fibreG: 2.5,
    ironMg: 0.7,
    contains: [],
    group: 'carb',
    snack: true,
    aliases: ['tortilla', 'flatbread', 'taco shell'],
    cuisines: ['latin-american'],
  },
  {
    id: 'chicken-fajita',
    name: 'Chicken fajita filling',
    serving: '1 cup',
    servingG: 180,
    kcal: 250,
    proteinG: 27,
    carbG: 10,
    fatG: 11,
    fibreG: 2,
    ironMg: 1.5,
    contains: ['meat'],
    group: 'protein',
    aliases: ['grilled chicken', 'pollo asado'],
    cuisines: ['latin-american'],
  },
  {
    id: 'arroz-con-pollo',
    name: 'Arroz con pollo',
    serving: '1 cup',
    servingG: 240,
    kcal: 340,
    proteinG: 20,
    carbG: 42,
    fatG: 10,
    fibreG: 2,
    ironMg: 2,
    contains: ['meat'],
    group: 'mixed',
    aliases: ['chicken and rice'],
    cuisines: ['latin-american'],
  },
  {
    id: 'guacamole',
    name: 'Guacamole',
    serving: 'half a cup',
    servingG: 115,
    kcal: 190,
    proteinG: 2.5,
    carbG: 10,
    fatG: 17,
    fibreG: 7,
    ironMg: 0.6,
    contains: [],
    group: 'fat',
    snack: true,
    aliases: ['avocado'],
    cuisines: ['latin-american'],
  },
  {
    id: 'feijoada',
    name: 'Feijoada',
    serving: '1 cup',
    servingG: 240,
    kcal: 380,
    proteinG: 24,
    carbG: 28,
    fatG: 18,
    fibreG: 9,
    ironMg: 3.8,
    contains: ['meat', 'pork'],
    group: 'mixed',
    aliases: ['bean stew'],
    cuisines: ['latin-american'],
  },
  {
    id: 'ceviche',
    name: 'Ceviche',
    serving: '1 cup',
    servingG: 180,
    kcal: 160,
    proteinG: 24,
    carbG: 8,
    fatG: 3,
    fibreG: 1,
    ironMg: 0.9,
    contains: ['fish'],
    group: 'protein',
    aliases: ['raw fish salad'],
    cuisines: ['latin-american'],
  },
  {
    id: 'queso-fresco',
    name: 'Queso fresco',
    serving: '50 g',
    servingG: 50,
    kcal: 145,
    proteinG: 9,
    carbG: 2,
    fatG: 11,
    fibreG: 0,
    ironMg: 0.2,
    contains: ['dairy'],
    group: 'dairy',
    snack: true,
    aliases: ['fresh cheese', 'cheese'],
    cuisines: ['latin-american'],
  },
  {
    id: 'refried-beans',
    name: 'Refried beans',
    serving: '1 cup',
    servingG: 240,
    kcal: 240,
    proteinG: 14,
    carbG: 36,
    fatG: 4,
    fibreG: 12,
    ironMg: 4.2,
    contains: [],
    group: 'protein',
    aliases: ['frijoles refritos', 'beans'],
    cuisines: ['latin-american'],
  },
];

const BY_ID = new Map(FOODS.map((food) => [food.id, food]));

export function getFood(id: string): Food | undefined {
  return BY_ID.get(id);
}

export function foodName(id: string): string {
  return BY_ID.get(id)?.name ?? id;
}

/* --------------------------- food she added ---------------------------- */

/**
 * Food she entered herself.
 *
 * A curated table is the reason the search is usable, and it is also the
 * reason it will never have her mother's biryani in it. The honest answer to
 * that is not a bigger table - it is letting her write the row, and being
 * clear on the screen about which rows she wrote.
 *
 * The id is a slug so the same dish logged twice groups in the quick-add
 * tally, and it is prefixed so nothing can ever collide with a real entry or
 * be mistaken for one by the coach's catalogue.
 */
export const CUSTOM_PREFIX = 'custom:';

export function customFoodId(name: string): string {
  const slug = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40);
  return `${CUSTOM_PREFIX}${slug || 'food'}`;
}

export function isCustomId(id: string): boolean {
  return id.startsWith(CUSTOM_PREFIX);
}

/** The row's food, whether it came from the table or from her. */
export function foodFor(meal: {
  foodId: string;
  custom?: CustomFood;
}): Food | undefined {
  if (meal.custom) {
    return {
      id: meal.foodId,
      name: meal.custom.name,
      serving: meal.custom.serving,
      // Unknown, and it is never shown for a custom food. Zero would read as
      // a claim; this is the one field she was not asked for.
      servingG: 0,
      kcal: meal.custom.kcal,
      proteinG: meal.custom.proteinG,
      carbG: meal.custom.carbG,
      fatG: meal.custom.fatG,
      fibreG: meal.custom.fibreG,
      ironMg: meal.custom.ironMg,
      // She was not asked what is in it, so nothing is claimed about
      // allergens. A custom row is never offered by the planner, only logged.
      contains: [],
      group: 'mixed',
    };
  }
  return BY_ID.get(meal.foodId);
}

/* ------------------------------ filtering ------------------------------ */

/**
 * The diet patterns, said in her words rather than in ours.
 *
 * Here rather than in a component because onboarding and You both ask the
 * question, and two screens that word the same setting differently are two
 * screens she has to reconcile herself.
 */
export const DIET_LABEL: Record<DietPattern, string> = {
  omnivore: 'I eat everything',
  halal: 'Halal',
  vegetarian: 'Vegetarian',
  vegan: 'Vegan',
};

export const DIET_HINT: Record<DietPattern, string> = {
  omnivore: 'Nothing left out',
  halal: 'No pork',
  vegetarian: 'No meat or fish',
  vegan: 'No animal products at all',
};

/** Allergens she can exclude. Meat and pork are handled by diet pattern. */
export const AVOIDABLE: { id: Allergen; label: string }[] = [
  { id: 'dairy', label: 'Dairy' },
  { id: 'gluten', label: 'Gluten' },
  { id: 'nuts', label: 'Nuts' },
  { id: 'egg', label: 'Egg' },
  { id: 'soy', label: 'Soy' },
  { id: 'fish', label: 'Fish' },
];

function allowedByPattern(food: Food, pattern: DietPattern): boolean {
  switch (pattern) {
    case 'vegan':
      return !food.contains.some((item) =>
        (['meat', 'pork', 'fish', 'egg', 'dairy'] as Allergen[]).includes(item),
      );
    case 'vegetarian':
      return !food.contains.some((item) =>
        (['meat', 'pork', 'fish'] as Allergen[]).includes(item),
      );
    case 'halal':
      return !food.contains.includes('pork');
    case 'omnivore':
      return true;
  }
}

/**
 * Everything she can eat. A food is excluded if her diet pattern rules it out
 * or if it contains anything on her avoid list - and the two are separate,
 * because "I do not eat meat" and "dairy makes me ill" fail differently and a
 * meal plan has to respect both.
 */
export function allowedFoods(pattern: DietPattern, avoid: string[]): Food[] {
  return FOODS.filter(
    (food) =>
      allowedByPattern(food, pattern) &&
      !food.contains.some((item) => avoid.includes(item)),
  );
}

/* --------------------------- region and search --------------------------- */

/**
 * A food with no region on it is an everyday item everywhere - eggs, oats,
 * chicken breast, milk. Those sort above other people's regional cooking and
 * below her own.
 */
export function isUniversal(food: Food): boolean {
  return food.cuisines === undefined || food.cuisines.length === 0;
}

export function isFrom(food: Food, cuisine: Cuisine | null): boolean {
  return cuisine !== null && (food.cuisines?.includes(cuisine) ?? false);
}

/**
 * Her cooking first, then the things everyone eats, then everything else -
 * and inside each band the table's own order, which is already curated.
 *
 * Nothing is removed. She may well cook Thai on a Tuesday, and a food table
 * that hides it because she once tapped "Pakistan" is a table she stops
 * trusting the first time it cannot find her dinner.
 */
export function sortForCuisine(foods: Food[], cuisine: Cuisine | null): Food[] {
  const rank = (food: Food): number =>
    isFrom(food, cuisine) ? 0 : isUniversal(food) ? 1 : 2;
  return foods
    .map((food, index) => ({ food, index }))
    .sort((a, b) => rank(a.food) - rank(b.food) || a.index - b.index)
    .map((entry) => entry.food);
}

/**
 * Does this food answer that search?
 *
 * Name and aliases both, because "lentils" and "yogurt" are what she types and
 * "Daal (masoor or moong)" and "Dahi" are what the table calls them. A
 * curated table only feels small when the search cannot find what is in it.
 */
export function foodMatches(food: Food, query: string): boolean {
  const needle = query.trim().toLowerCase();
  if (needle === '') return true;
  if (food.name.toLowerCase().includes(needle)) return true;
  return (food.aliases ?? []).some((alias) => alias.includes(needle));
}

/**
 * Search results, best first: a name that starts with what she typed beats a
 * name that merely contains it, and both beat an alias match.
 */
export function searchFoods(
  foods: Food[],
  query: string,
  cuisine: Cuisine | null,
): Food[] {
  const needle = query.trim().toLowerCase();
  if (needle === '') return sortForCuisine(foods, cuisine);

  const scored = foods
    .map((food) => {
      const name = food.name.toLowerCase();
      if (name.startsWith(needle)) return { food, score: 0 };
      if (name.includes(needle)) return { food, score: 1 };
      if ((food.aliases ?? []).some((alias) => alias.startsWith(needle)))
        return { food, score: 2 };
      if ((food.aliases ?? []).some((alias) => alias.includes(needle)))
        return { food, score: 3 };
      return null;
    })
    .filter((entry): entry is { food: Food; score: number } => entry !== null);

  // Her own region breaks a tie inside a score band, so searching "curry"
  // in Lahore leads with karahi rather than with Thai green curry.
  return scored
    .sort(
      (a, b) =>
        a.score - b.score ||
        (isFrom(a.food, cuisine) ? 0 : 1) - (isFrom(b.food, cuisine) ? 0 : 1),
    )
    .map((entry) => entry.food);
}

export interface Nutrients {
  kcal: number;
  proteinG: number;
  carbG: number;
  fatG: number;
  fibreG: number;
  ironMg: number;
}

export const NO_NUTRIENTS: Nutrients = {
  kcal: 0,
  proteinG: 0,
  carbG: 0,
  fatG: 0,
  fibreG: 0,
  ironMg: 0,
};

export function scale(food: Food, servings: number): Nutrients {
  return {
    kcal: food.kcal * servings,
    proteinG: food.proteinG * servings,
    carbG: food.carbG * servings,
    fatG: food.fatG * servings,
    fibreG: food.fibreG * servings,
    ironMg: food.ironMg * servings,
  };
}

export function addNutrients(a: Nutrients, b: Nutrients): Nutrients {
  return {
    kcal: a.kcal + b.kcal,
    proteinG: a.proteinG + b.proteinG,
    carbG: a.carbG + b.carbG,
    fatG: a.fatG + b.fatG,
    fibreG: a.fibreG + b.fibreG,
    ironMg: a.ironMg + b.ironMg,
  };
}

export function roundNutrients(value: Nutrients): Nutrients {
  return {
    kcal: Math.round(value.kcal),
    proteinG: Math.round(value.proteinG),
    carbG: Math.round(value.carbG),
    fatG: Math.round(value.fatG),
    fibreG: Math.round(value.fibreG * 10) / 10,
    ironMg: Math.round(value.ironMg * 10) / 10,
  };
}

/**
 * Iron for menstruating women. Notably higher than the male figure, and the
 * gap is the single most common nutritional shortfall in this population.
 */
export const IRON_TARGET_MG = 18;

export const IRON_NOTE =
  'Plant iron - daal, chana, spinach - absorbs far better alongside vitamin C. A squeeze of lemon or some salad with the meal does more than the amount on the label suggests. Tea and coffee with the meal do the opposite.';
